name: GitHub SSH

on:
  push:
    branches:
    - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: change password
        run: echo "runner:runner" | sudo chpasswd

      - name: ngrok
        run: |
          curl -skL -o /tmp/ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip -d /tmp /tmp/ngrok.zip
          chmod +x /tmp/ngrok
          /tmp/ngrok authtoken ${{ secrets.NGROK_TOKEN }}
          /tmp/ngrok tcp 22 --log stdout
